[directory]
truncation_length = 1

[git_branch]
symbol = "ᚠ "

[golang]
disabled = true

[kubernetes]
format = '[⚓ $context](bright-blue) '
disabled = false

[time]
time_format = "%T"
format = "🕙 $time($style) "
style = "bright-white"
disabled = false
