---
- name: link shared dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "~/.dotfiles/bash_profile", dest: "~/.bash_profile"}
    - { src: "~/.dotfiles/bashrc", dest: "~/.bashrc"}
    - { src: "~/.dotfiles/gitconfig", dest: "~/.gitconfig"}
    - { src: "~/.dotfiles/vimrc", dest: "~/.vimrc"}

# - name: link dotfiles for macOS
#   when: ansible_os_family == "Darwin"
#   file:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     state: link
#   loop:
#     - { src: "~/.dotfiles/vscode.json", dest: "~/Library/Application Support/Code/User/settings.json" }
