# Playbook for managing Darwin machine
---
- name: Playbook to manage Darwin dotfiles
  hosts: localhost
  connection: local
  tasks:
    - name: load custom vars
      include_vars: ../vars/darwin.yaml
      tags:
        - always

    - name: Install brew formulas
      homebrew:
        name: "{{ brew_formulas }}"
        state: present
        update_homebrew: true

    - name: Install brew cask formulas
      homebrew:
        name: "{{ brew_cask_formulas }}"
        state: present
        update_homebrew: true
    
    - include: tasks/link_files.yaml
      tags:
        - links

    - name: Install starship
      shell:
        cmd: sh -s -- -y
        stdin: "{{ starship_installer.content }}"
    
    - name: Download starship
      uri:
        url: https://starship.rs/install.sh
        return_content: yes
      register: starship_installer
