# Playbook for managing Darwin machine
---
- name: Playbook to manage Darwin dotfiles
  hosts: localhost
  connection: local
  tasks:
    - name: load custom vars
      include_vars: ../vars/linux.yaml
      tags:
        - always
    
    - include: tasks/link_files.yaml
      tags:
        - links
    
    - name: Download starship
      uri:
        url: https://starship.rs/install.sh
        return_content: yes
      register: starship_installer

    - name: Install starship
      shell:
        cmd: sh -s -- -y
        stdin: "{{ starship_installer.content }}"
